name: Main Branch CI

on:
  push:
    branches: [ main ]

jobs:
  test:
    name: Test and Build
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: '1.24'

    - name: Cache Go modules
      uses: actions/cache@v4
      with:
        path: |
          ~/.cache/go-build
          ~/go/pkg/mod
        key: ${{ runner.os }}-go-1.24-${{ hashFiles('**/go.sum') }}
        restore-keys: |
          ${{ runner.os }}-go-1.24-
          ${{ runner.os }}-go-

    - name: Install dependencies
      run: make deps

    - name: Run format check
      run: make format

    - name: Run linter
      run: make lint

    - name: Run tests
      run: make test-coverage

    - name: Build
      run: make build

    - name: Security scan
      run: make security

    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v3
      with:
        file: ./coverage.out
        flags: unittests
        name: codecov-umbrella

  release-check:
    name: Release Readiness
    runs-on: ubuntu-latest
    needs: test
    if: github.ref == 'refs/heads/main'

    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Check if version tag needed
      run: |
        echo "Main branch updated. Consider creating a release tag if this contains breaking changes or new features."
