name: Pull Request Checks

on:
  pull_request:
    branches: [ main ]

jobs:
  test:
    name: Test and Lint
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: '1.24'

    - name: Cache Go modules
      uses: actions/cache@v4
      with:
        path: |
          ~/.cache/go-build
          ~/go/pkg/mod
        key: ${{ runner.os }}-go-1.24-${{ hashFiles('**/go.sum') }}
        restore-keys: |
          ${{ runner.os }}-go-1.24-
          ${{ runner.os }}-go-

    - name: Install dependencies
      run: make deps

    - name: Check formatting
      run: |
        make format
        if [ -n "$(git diff --name-only)" ]; then
          echo "Code is not properly formatted. Please run 'make format' and commit the changes."
          git diff
          exit 1
        fi

    - name: Run linter
      run: make lint

    - name: Run tests
      run: make test-coverage

    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v3
      with:
        file: ./coverage.out
        flags: unittests
        name: codecov-umbrella

    - name: Build
      run: make build

    - name: Security scan
      run: make security
